name: Gradle CI/CD

on:
  push:
    branches:
      - main
      - master
permissions:
  id-token: write
  contents: read

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout Code
      - name: Checkout Source Code
        uses: actions/checkout@v4

      # Setup Java
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      # Give Gradle Permission
      - name: Give Gradle Permission
        run: chmod +x gradlew

      # Build Project
      - name: Build Gradle Project
        run: ./gradlew build

      # Build Docker Image
      - name: Build Docker Image
        run: docker build -t gradle-build-test:latest .

      #################################################
      # Push to Docker Hub with New Token
      #################################################

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker Image
        run: |
          docker tag gradle-build-test:latest \
          ${{ secrets.DOCKER_USERNAME }}/gradle-build-test:version02

      - name: Push to Docker Hub
        run: |
          docker push \
          ${{ secrets.DOCKER_USERNAME }}/gradle-build-test:version02

      #################################################
      # Push to Amazon ECR
      #################################################

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.AWS_REGION }}
      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE}}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag Docker Image for ECR
        run: |
          docker tag gradle-build-test:latest \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/gradle-hello-app:version02

      - name: Push to Amazon ECR.
        run: |
          docker push \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/gradle-hello-app:version02